### ISSUE TITLE
How to Obtain ChainFinder？

### ISSUE THREAD

**Issue by lirris1** [ChongJenniferZhang/CLCA_WGS#1]
I was trying to access the ChainFinder software from the link in your paper (https://software.broadinstitute.org/cancer/cga/chainfinder), but it seems to be down. Could you please tell me how to get and use this software now?

Thanks!

**Comment by ChongJenniferZhang** [comment]
> I was trying to access the ChainFinder software from the link in your paper (https://software.broadinstitute.org/cancer/cga/chainfinder), but it seems to be down. Could you please tell me how to get and use this software now?
> 
> Thanks!

Hi! Thank you for your interest in our paper. I just tried downloading the software again using the link, but unfortunately, it still doesn't seem to be working properly. We actually mentioned this article "Punctuated Evolution of Prostate Cancer Genomes" as the source of the software. I'm really sorry that it's currently not available. However, because of licensing permissions, I can't directly give you a copy.  I'll keep a close eye on the situation and let you know as soon as it becomes downloadable again. Thank you so much.

**Comment by xinxiangxin** [comment]
Hi! How are you! I was trying to access the chainfinder software from your parper, but the link is bad. I want to know how to get the software.

**Comment by Mingxi-HUANG-Sunnia** [comment]
![Image](https://github.com/user-attachments/assets/bea7238f-4775-4c3c-bbe5-30bf154034eb)

**Comment by Mingxi-HUANG-Sunnia** [comment]
Hi! I have contacted the first author of ChainFinder regarding the issue of being unable to download the software. He suggested seeking a copy from researchers who have recently used it. Would you be able to provide one? Thank you very much!

![Image](https://github.com/user-attachments/assets/a2a2c062-0f44-48c8-b3b2-be63b793d8dc)

**Comment by eesiribloom** [comment]
was there a solution to this?
